[[constraint]]
  branch = "master"
  name = "github.com/berkmancenter/ridge"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/gonum/blas"

[[constraint]]
  branch = "master"
  name = "github.com/gonum/floats"

[[constraint]]
  branch = "master"
  name = "github.com/gonum/matrix"

[[constraint]]
  branch = "errors"
  name = "github.com/gonum/plot"

[[constraint]]
  branch = "master"
  name = "github.com/gonum/stat"

[[constraint]]
  name = "github.com/kniren/gota"
  version = "0.9.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/lytics/anomalyzer"

[[constraint]]
  name = "github.com/mash/gokmeans"
  version = "0.1.0-alpha"

[[constraint]]
  name = "github.com/montanaflynn/stats"
  version = "0.3.0"

[[constraint]]
  name = "github.com/pachyderm/pachyderm"
  version = "1.7.10"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[constraint]]
  name = "github.com/sajari/regression"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/sjwhitworth/golearn"

[[constraint]]
  name = "github.com/tensorflow/tensorflow"
  version = "1.11.0"

[[constraint]]
  branch = "master"
  name = "gonum.org/v1/gonum"

[prune]
  go-tests = true
  unused-packages = true
